# vim:sw=2:et:

# Use a real VM so we can install all the packages we want.
sudo: required

language: erlang
notifications:
  email:
    - bargenson@gmail.com
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu precise contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - elixir
otp_release:
  - "19.0"

script: make

cache:
  apt: true
